.\"-*- nroff -*-
.TH YASUB "1" "May 2018" "YASched 1.0" "User Commands"
.SH "NAME"
yasub \- submit a job to YASched computing environment.
.SH "SYNOPSIS"
.B yasub
[\fIOPTIONS\fR] \fIEXEC\fR
.SH "DESCRIPTION"
.PP
Submit a job with binary \fIEXEC\fR to YASched computing environment.
.PP
Mandatory arguments to long options are mandatory for short options too.
.TP
\fB\-z\fR, \fB\-\-zone\fR=\fIID\fR
specify id of the zone that will contain
the submitted job
.TP
\fB\-j\fR, \fB\-\-jobname\fR=\fINAME\fR
specify name of the submitted job
.SH "AUTHOR"
.PP
Writen by Luke Huang <lukehuang.ca@gmail.com>.
.SH "REPORTING BUGS"
Please report bugs to lukehuang.ca@gmail.com.
.SH "COPYRIGHT"
Copyright \(co 2018 Luke Huang <lukehuang.ca@gmail.com>
.SH "SEE ALSO"
