### Makefile --- 

## Author: <lukehuang.ca@gmail.com>

TARGETS=publish confidential

$(TARGETS):
	@echo "  MK	  $@"
	@make -C $@ --no-print-directory

default: $(TARGETS)

.PHONY: publish confidential

### Makefile ends here
